#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	/sbin/ifup -a
	ifname=accnic0
	if [ -d "/sys/class/net/${ifname}" ]; then
		/sbin/ip link set dev "$ifname" up &&
		/sbin/ip addr add "10.0.0.1/24" dev "$ifname"
	fi
#	/sbin/ifup eth0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
#	/sbin/ifdown eth0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

